### PR TITLE
handle SSHFP records

### PR DESCRIPTION
**Pull request by rds13**
A simple proposal to handle SSFP records in DNS configuration.

### CODE REVIEW

**Comment by bertvv** [comment]
Cool, can you add some documentation for this feature in the README? You can add your name to the contributor list as well. ;-)

**Comment by bertvv** [comment]
Also, it's best to rebase your code to the latest revision, I've merged some PRs. Also, I hope I've fixed the travis build script, so it should succeed next time.

**Comment by rds13** [comment]
Thx @bertvv for your comments. I've updated my PR and add some minimal documentation.
Also the travis build seems to be fixed.

**Comment by bertvv** [comment]
Thank you!

**Pull request merged**
