### PR TITLE
Replace manual Docker tests with Molecule

### PR DESCRIPTION
**Pull request by RobinOphalvens**
### Abstract
  
Instead of complex scripts in order to create Docker containers, Molecule allows developers to easily and quickly test their roles  by automatically creating containers which are configured by readable yaml configuration files. Molecule does this by leveraging Ansible's [docker_container](https://docs.ansible.com/ansible/latest/modules/docker_container_module.html) module. 

The proposed Molecule configuration is essentially the automated version of the docker_tests branch, all done with a single command! An example of a working .travis.yml file is also provided. 

In **molecule.yml**, two Centos 7 containers are defined which will fulfill the master and slave role. The images are specifically chosen as they are Ansible compatible and can run systemd in them. Any Ansible/Systemd compatible image that is also supported by this role should be able to run with Molecule. 

**converge.yml** holds the the testing variables as well as two tasks which will transfer the automated acceptance tests to the containers. These two files are located under `molecule/default/files`

**verify.yml** is the playbook that will launch the automated tests. 

### Requirements and installation

1. Docker should be present on the system.
2. As recommended by the [Molecule documentation](https://molecule.readthedocs.io/en/latest/index.html), a Python virtual environment is highly recommended
3. Install Molecule, the Docker driver and python-netaddr with `python3 -m pip install molecule docker netaddr`. 
4. Verify that Molecule is installed with either `molecule --version` or `molecule --help`

### Testing procedure

1. Clone the repo
2. Navigate to the root of the role
3. Run `molecule test`

The Molecule test command will **always** destroy the containers at the end of the testing procedure. For development purposes, use `molecule converge` instead since it will keep the containers alive. `molecule login` also allows access to the container through an interactive shell.  

`molecule verify` can at any time be run in a converged state to verify that BIND is working. 

**Note**: this configuration, specifically the automated acceptance tests, assumes that the default Docker bridge network is being used. This means that NS1 should receive 172.17.0.2 as IPv4 while NS2 receives 172.17.0.3. If you receive errors during the verify stage, you might need to change the **verify.yml* playbook according to your network setup.

### CODE REVIEW

**Comment by RobinOphalvens** [comment]
More information regarding container configuration can be found here: 
https://molecule.readthedocs.io/en/latest/configuration.html

**Comment by bertvv** [comment]
This is awesome! Will be checking this as soon as I can. Thank you so much!

**Comment by RobinOphalvens** [comment]
You're welcome!

I've made a few changes in the meantime to the verify stage that is reponsible for executing the BAT tests. Now both the master and the slave server will be tested with DNS queries, instead of only the master server.

**Comment by blofeldthefish** [comment]
Hi @RobinOphalvens, I would like to offer my thanks too.  This does indeed look very promising.   Just a quick question, is it a straightforward task to add additional docker images for testing, to maintain validating the various Operating System flavours which this role supports.

**Comment by RobinOphalvens** [comment]
Hi @blofeldthefish, I can assure you this is indeed a straightforward process. The configuration of the desired containers is done under the `platforms` section in `molcule/default/molecule.yml` .  Have a look at the code below where I swapped the Centos 7 containers with an Ubuntu 18.04 and Debian9 image and added a third container which will be another slave server: 

```yaml
platforms:
  #Set name and hostname
  - name: ns1
    hostname: ns1
    #Specify which image should be used. Geerlingguys images are Ansible compatible and have Systemd installed
    image: "geerlingguy/docker-ubuntu1804-ansible:latest"
    #Command to execute when the container starts
    command: ""
    #Volumes to mount within the container. Important to enable systemd
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    #Give extended privileges to the container. Necessary for Systemd to operate within the container. 
    # DO NOT use extended privileges in a production environment!
    privileged: true
    #Allocate pseudo-TTY
    tty: True
    environment:
      container: docker
  

  - name: ns2
     hostname: ns2
     image: "geerlingguy/docker-debian9-ansible:latest"
     command: ""
     volumes:
       - /sys/fs/cgroup:/sys/fs/cgroup:rw
     privileged: true
     tty: True
     environment:
       container: docker

  - name: ns3
    hostname: ns3
    image: "geerlingguy/docker-centos7-ansible:latest"
    command: "/usr/sbin/init"
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    privileged: true
    tty: True 
    environment:
      container: docker
```

So essentially, to change the operating system you would like to test, you only have to edit the image option with a compatible image. Adding additional containers is easy too since you can basically copy/paste and edit a few settings (name,hostname, image). Note that when using a Debian/Ubuntu image however, you will have to edit the `command` option (I left it blank between quotes) since `/usr/sbin/init` will give errors. 

I'll admit that the `verify.yml` Ansible playbook, which will launch the acceptance tests, is a bit inefficient at the moment since you have to manually add two tasks for every additional container you would like to test (run the test and display the result with the IP of the container as an argument).

I hope this answers your question!

**Comment by bertvv** [comment]
What @blofeldthefish means is: we will want to test the role on several platforms in parallel, i.e. the distros mentioned in meta/main.yml. Now we have an environment matrix in .travis.yml that specifies the distro and version and starts a test run for that specific distro.

**Comment by RobinOphalvens** [comment]
Yes, I believe I'm starting to understand what you are trying to say. Apologies, it seems I have misinterpreted the question. 

At the moment, the different operating system images that are to be used are hardcoded within the the `molecule.yml` file but I believe I might be able to apply the build matrix as specified in meta/main and .travis.yml. I'll have a look at it ASAP.

**Comment by RobinOphalvens** [comment]
Update: I currently have a local working solution using Geerlings images. Next step is seeing if this also works for @bertvv images. Expect a commit later this evening

**Comment by bertvv** [comment]
Frankly, don't bother with my Docker images for Ansible testing. I haven't been able to maintain them for ages and geerlingguy's images fulfill the same purpose. I created these way back when there was nothing available, but I will gladly drop them in favour of a well-supported alternative...

**Comment by RobinOphalvens** [comment]
@bertvv @blofeldthefish I have attempted to implement the OS matrix. Is this perhaps the solution you are looking for?

**Comment by bertvv** [comment]
Yep, it looks like it is exactly that!

I'm struggling with setting up Docker on my machine (Fedora 32), I haven't been able to get it working yet.

**Comment by RobinOphalvens** [comment]
Best of luck in that case! Just keep in mind that the latest commit requires you to set the variables outside the yaml file, just like docker-tests.sh.

Something like this then:

```bash
DISTRIBUTION=centos VERSION=7 molecule test

DISTRIBUTION=debian VERSION=9 molecule converge
```

I myself run docker on a ubuntu 20.04 VM since docker on my host PC occasionally causes it to log out of the user session and restart the machine while running the containers in the background. The fact that Docker is directly available in the 20.04 repos is a nice bonus as well.

**Comment by bertvv** [comment]
Yeah, I guess I'll have to set up an Ubuntu VM as test environment as well. Downside is I won't be able to test anything related to SELinux in that case. I'm considering reverting to Vagrant + VirtualBox for testing what's not possible in Docker.

**Comment by bertvv** [comment]
Okay, I was finally able to set up an Ubuntu test VM and successfully run molecule. I have a suggestion for `molecule.yml`. Instead of `${DISTRIBUTION}${VERSION}`, maybe it's a little more convenient to use `${MOLECULE_DISTRO:-centos7}`. This way, we only need to specify one variable on the command line, and if we forget, it uses `centos7` as a default value.

Credits for this idea: Jeff Geerling <https://www.jeffgeerling.com/blog/2018/testing-your-ansible-roles-molecule>

**Comment by bertvv** [comment]
I also have a suggestion for `converge.yml`: instead of naming the role `ansible-role-bind` (the name of the directory with the role if you do a git clone), I think it's better to use the name as published on Ansible Galaxy, i.e. bertvv.bind. The directory should be named accordingly, of course.

Again, this is based on the way Jeff Geerling does it. See:
- <https://github.com/geerlingguy/ansible-role-haproxy/blob/master/.travis.yml> and 
- <https://github.com/geerlingguy/ansible-role-haproxy/blob/master/molecule/default/converge.yml>

**Comment by RobinOphalvens** [comment]
Excellent suggestions! I'll try to review and incorporate them ASAP. Thanks!

**Comment by bertvv** [comment]
When those are done, I'm ready to merge this. And then I can get to merging other open PRs and run tests on those. I'll finally be able to move this project forward again. So thanks a lot for this contribution!

**Comment by RobinOphalvens** [comment]
Now this is just weird. The Ubuntu containers are suddenly unable to download the BIND role software dependencies such as python-netaddr, bind9, etc. 

Let's see if the `pre_build_image` option is causing this issue or not.

**Comment by RobinOphalvens** [comment]
All right, so it seems the `pre_build_image` option was indeed the culprit. I'm not sure what the relation is between specifying that the image from Geerling is pre-build and the Ubuntu containers not being able to find the necessary packages. It's something I'll have a look at later. 

Nevertheless, the suggestions were succesfully implemented and should be working as desired. While I was at it, I've added the `MOLECULE_DOCKER_COMMAND` as well with default value` "" `. 
Not that it's really needed with this role but it's a nice-to-have, I guess. 

Hope you like it!

**Comment by bertvv** [comment]
Merged! Thank you!

**Comment by RobinOphalvens** [comment]
You a very much welcome! 

When I'll get more time on my hands, I'll look to apply Molecule to more of your roles where possible.

**Comment by bertvv** [comment]
After merging, I made a few more changes, specifically:

- Fix yamllint and ansible-lint warnings (this should increase the role's score on Ansible Galaxy)
- Simplify verify.yml. The BATS script is a black box test and should be executed from outside the containers. It's now executed from localhost. I was also able to get rid of the hard coded IP addresses and use those from the Ansible facts.

**Comment by RobinOphalvens** [comment]
Awesome! I've refrained from putting the lint checks in the commits since I was never able to make it work on my local machine so I wasn't sure how it would transition to CI environment. 

I'm currently using your suggestions and changes for a pull request for your samba role but I'm having issues with Travis CI where's it's having trouble syncing with my Github repos. Hope I can fix that one soon.

**Comment by bertvv** [comment]
There were problems with Github last night, I had that too. Should be fixed now, though. Thanks for your continued help!

**Pull request merged**
