### PR TITLE
support allow-recursion

### PR DESCRIPTION
**Pull request by dachary**

### CODE REVIEW

**Comment by dachary** [comment]
I'll fix those errors

**Comment by bertvv** [comment]
Thank you for contributing this!

It's probably only a question of giving `bind_allow_recursion` a default value (probably `any`) in  defaults/main.yml. Then you don't have to check for the existence in the template anymore.

Also, can you add some info on this new variable in the documentation in README.md and add yourself to the contributor list?

**Comment by dachary** [comment]
@bertvv I will, thanks for the guidance :-)

**Comment by dachary** [comment]
The tests are happy, does it look good to you ?

**Comment by bertvv** [comment]
Sorry for the delay and thanks again! I'll release a new version shortly

**Pull request merged**
