### PR TITLE
Added support of Bind Catalog Zone feature

### PR DESCRIPTION
**Pull request by pavel-z1**
Hi,

I have added support of Bind Catalog Zone feature to the bind role.

This PR contains many changes and minor edits that were required for my environment. Including possibility to add zone for Hashikorp Consul.
I suggest to add this code as it is, since I don’t have enough free time to make changes to it during review process.

If the repository owner has comments and suggestions, you can make edits to this PR yourself.

### CODE REVIEW

**Comment by GR360RY** [comment]
@pavel-z1 , thanks for your contribution. I will go over the changes this week and update.

**Comment by GR360RY** [comment]
@pavel-z1 , thanks for the PR, but it cannot be accepted in the current form. Some of the logic implemented in your branch is already available in master (for ex. zone type auto-detection, forward zone types and "slave on master"). 

For ex. adding consul forward type zone can be done with forward type zone:

```yaml
  - name: consul
     forwarders:
       - '127.0.0.1 port 8600'
```

The addition of catalog zone type is a welcome change, but this will require some work on your part before I can merge it:

* Remove all the logic not related to catalog zones
* Use explicit "type" variable per zone to define catalog zone
* Possibly move catalog zone definition to bind_zones together with other zone types.

**Comment by pavel-z1** [comment]
Hi @GR360RY 

> For ex. adding consul forward type zone can be done with forward type zone:
>
>  - name: consul
>     forwarders:
>       - '127.0.0.1 port 8600'

Consul forward zone can't be configured with this.
Because this construction generate master or slave zone, like this:
```
zone "consul" IN {
  type master;
  file "/var/named/consul.db";
  notify yes;
  allow-update { none; };
};
```
But consul need forward only zone, like:
```
zone "consul" IN {
  type forward;
  forward only;
  forwarders { 127.0.0.1 port 8600; };
};
```

Regarding this:
> Remove all the logic not related to catalog zones

I cannot do this for two reasons:
1. Many additional featured and options were added to this PR as additional features which extend catalog zone too. Full list of   options you can find here in readme file https://github.com/bertvv/ansible-role-bind/pull/146/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5
2. Removing all features except catalog zone from this PR will lead to the fact that all the necessary functionality of Named, which is necessary for my work, will stop working. I've previously tried to send here PRs for with granularly changes, but these PRs were not reviewed from July till October. Examples of these PS:
https://github.com/bertvv/ansible-role-bind/pull/124
https://github.com/bertvv/ansible-role-bind/pull/125
Therefore, I've shared my work with you with to add them when you will have time. I've added note that don't have so huge time to get PR reviews during months.

Now, unfortunately I don't have free time to rebuild this logic from start again. I lot of time should be spend to stabilise catalog zone feature again in way that you propose. 

Therefore, I propose to use this PR as it is, but just remove from this PR features, described here:
https://github.com/bertvv/ansible-role-bind/pull/124
https://github.com/bertvv/ansible-role-bind/pull/125

If this is will not acceptable for you, you can use this PR as you need.
I've allowed changes to this PR for repository owner.

**Comment by bertvv** [comment]
I appreciate the work you did on these changes and that you are willing to share them with us.

However, merging this PR would pose too much of a risk to the existing functionality, especially since (according to your initial comment) it contains changes that are specific to a particular environment. Additionaly, recent changes now cause merge conflicts.

I'm truly sorry, but we don't have enough time eiter to thoroughly review this contribution and test it.

**Pull request closed without merging**
